// <auto-generated />
using System;
using BinanceBot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BinanceBot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260418174735_AddMaxOpenPositions")]
    partial class AddMaxOpenPositions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BinanceBot.Domain.BacktestRuns.BacktestRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("FinalBalance")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<DateTimeOffset>("FromUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("MaxDrawdownPct")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("Sharpe")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("StrategyId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ToUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("WinRate")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_BacktestRuns_Status");

                    b.HasIndex("StrategyId", "StartedAt")
                        .HasDatabaseName("IX_BacktestRuns_Strategy_Started");

                    b.ToTable("BacktestRuns", (string)null);
                });

            modelBuilder.Entity("BinanceBot.Domain.BacktestRuns.BacktestTrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BacktestRunId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Pnl")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("Price")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BacktestRunId", "SequenceNo")
                        .IsUnique()
                        .HasDatabaseName("UX_BacktestTrades_Run_Seq");

                    b.ToTable("BacktestTrades", (string)null);
                });

            modelBuilder.Entity("BinanceBot.Domain.Balances.VirtualBalance", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("Equity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<Guid>("IterationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastResetAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<int>("ResetCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("StartingBalance")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("VirtualBalances", null, t =>
                        {
                            t.HasCheckConstraint("CK_VirtualBalances_ModeIdParity", "[Id] = [Mode]");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentBalance = 100m,
                            Equity = 100m,
                            IterationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Mode = 1,
                            ResetCount = 0,
                            StartedAt = new DateTimeOffset(new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StartingBalance = 100m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            CurrentBalance = 0m,
                            Equity = 0m,
                            IterationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Mode = 2,
                            ResetCount = 0,
                            StartedAt = new DateTimeOffset(new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StartingBalance = 0m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            CurrentBalance = 0m,
                            Equity = 0m,
                            IterationId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Mode = 3,
                            ResetCount = 0,
                            StartedAt = new DateTimeOffset(new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StartingBalance = 0m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("BinanceBot.Domain.Instruments.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseAsset")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("MaxQty")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("MinNotional")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("MinQty")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<string>("QuoteAsset")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("StepSize")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TickSize")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasDatabaseName("UX_Instruments_Symbol");

                    b.ToTable("Instruments", (string)null);
                });

            modelBuilder.Entity("BinanceBot.Domain.MarketData.BookTicker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AskPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("AskQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("BidPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("BidQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("UpdateId")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasDatabaseName("UX_BookTickers_Symbol");

                    b.ToTable("BookTickers", (string)null);
                });

            modelBuilder.Entity("BinanceBot.Domain.MarketData.Kline", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ClosePrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<DateTimeOffset>("CloseTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("HighPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<decimal>("LowPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("OpenPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<DateTimeOffset>("OpenTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("QuoteVolume")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TakerBuyBaseVolume")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("TakerBuyQuoteVolume")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<int>("TradeCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Volume")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Interval", "OpenTime")
                        .IsUnique()
                        .HasDatabaseName("UX_Klines_Symbol_Interval_OpenTime");

                    b.HasIndex("Symbol", "Interval", "IsClosed", "OpenTime")
                        .HasDatabaseName("IX_Klines_ReadPath");

                    b.ToTable("Klines", (string)null);
                });

            modelBuilder.Entity("BinanceBot.Domain.MarketData.OrderBookSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AsksJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BidsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("LastUpdateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "CapturedAt")
                        .HasDatabaseName("IX_OrderBookSnapshots_Symbol_CapturedAt");

                    b.ToTable("OrderBookSnapshots", (string)null);
                });

            modelBuilder.Entity("BinanceBot.Domain.Orders.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("CumulativeQuoteQty")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<long?>("ExchangeOrderId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ExecutedQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("StopPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<long?>("StrategyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("TakeProfit")
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("TimeInForce")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeOrderId")
                        .HasDatabaseName("IX_Orders_ExchangeOrderId")
                        .HasFilter("[ExchangeOrderId] IS NOT NULL");

                    b.HasIndex("StrategyId")
                        .HasDatabaseName("IX_Orders_StrategyId");

                    b.HasIndex("ClientOrderId", "Mode")
                        .IsUnique()
                        .HasDatabaseName("UX_Orders_ClientOrderId_Mode");

                    b.HasIndex("Symbol", "Status", "UpdatedAt")
                        .HasDatabaseName("IX_Orders_Symbol_Status_Updated");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("BinanceBot.Domain.Orders.OrderFill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Commission")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<string>("CommissionAsset")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("ExchangeTradeId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("FilledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "ExchangeTradeId")
                        .IsUnique()
                        .HasDatabaseName("UX_OrderFills_Order_ExchangeTrade");

                    b.ToTable("OrderFills", (string)null);
                });

            modelBuilder.Entity("BinanceBot.Domain.Positions.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AverageEntryPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("ExitPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("MarkPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("RealizedPnl")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("StopPrice")
                        .HasColumnType("decimal(18,8)");

                    b.Property<long?>("StrategyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("TakeProfit")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("UnrealizedPnl")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId")
                        .HasDatabaseName("IX_Positions_StrategyId");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("IX_Positions_Status_Updated");

                    b.HasIndex("Symbol", "Mode")
                        .IsUnique()
                        .HasDatabaseName("UX_Positions_Symbol_Mode_Open")
                        .HasFilter("[Status] = 1");

                    b.HasIndex("Mode", "Status", "UpdatedAt")
                        .HasDatabaseName("IX_Positions_Mode_Status");

                    b.ToTable("Positions", (string)null);
                });

            modelBuilder.Entity("BinanceBot.Domain.RiskProfiles.RiskProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CapsAdminNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CircuitBreakerReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CircuitBreakerStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CircuitBreakerTrippedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ConsecutiveLosses")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentDrawdownPct")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("MaxConsecutiveLosses")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxDrawdown24hPct")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("MaxDrawdownAllTimePct")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("MaxOpenPositions")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxPositionCap")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("MaxPositionSizePct")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("PeakEquity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("RealizedPnl24h")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("RealizedPnlAllTime")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal?>("RiskPerTradeCap")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("RiskPerTradePct")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("RiskProfiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CircuitBreakerStatus = 1,
                            ConsecutiveLosses = 0,
                            CurrentDrawdownPct = 0m,
                            MaxConsecutiveLosses = 3,
                            MaxDrawdown24hPct = 0.05m,
                            MaxDrawdownAllTimePct = 0.25m,
                            MaxOpenPositions = 2,
                            MaxPositionSizePct = 0.10m,
                            PeakEquity = 0m,
                            RealizedPnl24h = 0m,
                            RealizedPnlAllTime = 0m,
                            RiskPerTradePct = 0.01m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            CircuitBreakerStatus = 1,
                            ConsecutiveLosses = 0,
                            CurrentDrawdownPct = 0m,
                            MaxConsecutiveLosses = 3,
                            MaxDrawdown24hPct = 0.05m,
                            MaxDrawdownAllTimePct = 0.25m,
                            MaxOpenPositions = 2,
                            MaxPositionSizePct = 0.10m,
                            PeakEquity = 0m,
                            RealizedPnl24h = 0m,
                            RealizedPnlAllTime = 0m,
                            RiskPerTradePct = 0.01m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            CircuitBreakerStatus = 1,
                            ConsecutiveLosses = 0,
                            CurrentDrawdownPct = 0m,
                            MaxConsecutiveLosses = 3,
                            MaxDrawdown24hPct = 0.05m,
                            MaxDrawdownAllTimePct = 0.25m,
                            MaxOpenPositions = 2,
                            MaxPositionSizePct = 0.10m,
                            PeakEquity = 0m,
                            RealizedPnl24h = 0m,
                            RealizedPnlAllTime = 0m,
                            RiskPerTradePct = 0.01m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("BinanceBot.Domain.Strategies.Strategy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SymbolsCsv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Strategies_Name");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Strategies_Status");

                    b.ToTable("Strategies", (string)null);
                });

            modelBuilder.Entity("BinanceBot.Domain.Strategies.StrategySignal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("BarOpenTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("EmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("StrategyId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("SuggestedPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("SuggestedQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal?>("SuggestedStopPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal?>("SuggestedTakeProfit")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId", "EmittedAt")
                        .HasDatabaseName("IX_StrategySignals_Strategy_Emitted");

                    b.HasIndex("StrategyId", "BarOpenTime", "Symbol")
                        .IsUnique()
                        .HasDatabaseName("UX_StrategySignals_Bar");

                    b.ToTable("StrategySignals", (string)null);
                });

            modelBuilder.Entity("BinanceBot.Domain.SystemEvents.SystemEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("IX_SystemEvents_OccurredAt");

                    b.HasIndex("EventType", "OccurredAt")
                        .HasDatabaseName("IX_SystemEvents_EventType_OccurredAt");

                    b.ToTable("SystemEvents", (string)null);
                });

            modelBuilder.Entity("BinanceBot.Domain.BacktestRuns.BacktestTrade", b =>
                {
                    b.HasOne("BinanceBot.Domain.BacktestRuns.BacktestRun", null)
                        .WithMany("Trades")
                        .HasForeignKey("BacktestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BinanceBot.Domain.Orders.OrderFill", b =>
                {
                    b.HasOne("BinanceBot.Domain.Orders.Order", null)
                        .WithMany("Fills")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BinanceBot.Domain.Strategies.StrategySignal", b =>
                {
                    b.HasOne("BinanceBot.Domain.Strategies.Strategy", null)
                        .WithMany("Signals")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BinanceBot.Domain.BacktestRuns.BacktestRun", b =>
                {
                    b.Navigation("Trades");
                });

            modelBuilder.Entity("BinanceBot.Domain.Orders.Order", b =>
                {
                    b.Navigation("Fills");
                });

            modelBuilder.Entity("BinanceBot.Domain.Strategies.Strategy", b =>
                {
                    b.Navigation("Signals");
                });
#pragma warning restore 612, 618
        }
    }
}
